export const SEND_MESSAGE = "SEND_MESSAGE";
export const GET_ALL_MESSAGE = "GET_ALL_MESSAGE";
export const UPDATE_GET_ALL_MESSAGE = "UPDATE_GET_ALL_MESSAGE";
export const CLEAR_ALL_MESSAGE = "CLEAR_ALL_MESSAGE";
export const SHOW_TOOGLE_LOADING = "SHOW_TOOGLE_LOADING";
export const SHOW_NETWORK_ERROR = "SHOW_NETWORK_ERROR"
